### ISSUE TITLE
Black page with error after install

### ISSUE THREAD

**Issue by Toweringmedia-clients** [magefan/module-conflict-detector#2]
Hello,
After installing this extension on a store with quite a few extensions I am getting the below error in the var/log folder.
app/code/Magefan/ConflictDetector/Block/Adminhtml/ConflictList.php on line 93

Please advise

**Comment by magefan** [comment]
Hello @toweringmedia  could you please share the whole error information?

**Comment by Toweringmedia-clients** [comment]
This is the only other part 

 

2018-03-12 21:11:56] main.CRITICAL: Notice: Undefined variable: status in

**Comment by magefan** [comment]
This issue was fixed in version 2.0.3. The current version is 2.0.4
