### ISSUE TITLE
Scope is not considered during detection

### ISSUE THREAD

**Issue by onlinebizsoft** [magefan/module-conflict-detector#4]
Look like it doesn't cover di scope adminhtml, frontend

**Comment by magefan** [comment]
@onlinebizsoft , we're working on this issue.

**Comment by onlinebizsoft** [comment]
@magefan do you have any update so far?

**Comment by magefan** [comment]
@onlinebizsoft , this has been fixed https://github.com/magefan/module-conflict-detector/commit/2c49169b6eea54643b9b88d872b07b185ab0caeb and will be included in the next release.
